[
  {
    id: "804",
    main: "Clouds",
    desc: "overcast clouds: 85-100%",
    icon: "04d  04n",
  },
  {
    id: "803",
    main: "Clouds",
    desc: "broken clouds: 51-84%",
    icon: "04d  04n",
  },
  {
    id: "802",
    main: "Clouds",
    desc: "scattered clouds: 25-50%",
    icon: "03d  03n",
  },
  { id: "801", main: "Clouds", desc: "few clouds: 11-25%", icon: "02d  02n" },
  { id: "800", main: "Clear", desc: "clear sky", icon: "01d  01n" },
  { id: "781", main: "Tornado", desc: "tornado", icon: "50d" },
  { id: "771", main: "Squall", desc: "squalls", icon: "50d" },
  { id: "762", main: "Ash", desc: "volcanic ash", icon: "50d" },
  { id: "761", main: "Dust", desc: "dust", icon: "50d" },
  { id: "751", main: "Sand", desc: "sand", icon: "50d" },
  { id: "741", main: "Fog", desc: "fog", icon: "50d" },
  { id: "731", main: "Dust", desc: "sand/dust whirls", icon: "50d" },
  { id: "721", main: "Haze", desc: "haze", icon: "50d" },
  { id: "711", main: "Smoke", desc: "smoke", icon: "50d" },
  { id: "701", main: "Mist", desc: "mist", icon: "50d" },
  { id: "622", main: "Snow", desc: "heavy shower snow", icon: "13d" },
  { id: "621", main: "Snow", desc: "shower snow", icon: "13d" },
  { id: "620", main: "Snow", desc: "light shower snow", icon: "13d" },
  { id: "616", main: "Snow", desc: "rain and snow", icon: "13d" },
  { id: "615", main: "Snow", desc: "light rain and snow", icon: "13d" },
  { id: "613", main: "Snow", desc: "shower sleet", icon: "13d" },
  { id: "612", main: "Snow", desc: "light shower sleet", icon: "13d" },
  { id: "611", main: "Snow", desc: "sleet", icon: "13d" },
  { id: "602", main: "Snow", desc: "heavy snow", icon: "13d" },
  { id: "601", main: "Snow", desc: "snow", icon: "13d" },
  { id: "600", main: "snow", desc: "light snow", icon: "13d" },
  { id: "531", main: "Rain", desc: "ragged shower rain", icon: "09d" },
  { id: "522", main: "Rain", desc: "heavy intensity shower rain", icon: "09d" },
  { id: "521", main: "Rain", desc: "shower rain", icon: "09d" },
  { id: "520", main: "Rain", desc: "light intensity shower rain", icon: "09d" },
  { id: "511", main: "Rain", desc: "freezing rain", icon: "13d" },
  { id: "504", main: "Rain", desc: "extreme rain", icon: "10d" },
  { id: "503", main: "Rain", desc: "very heavy rain", icon: "10d" },
  { id: "502", main: "Rain", desc: "heavy intensity rain", icon: "10d" },
  { id: "501", main: "Rain", desc: "moderate rain", icon: "10d" },
  { id: "500", main: "Rain", desc: "light rain", icon: "10d" },
  { id: "321", main: "Drizzle", desc: "shower drizzle", icon: "09d" },
  {
    id: "314",
    main: "Drizzle",
    desc: "heavy shower rain and drizzle",
    icon: "09d",
  },
  { id: "313", main: "Drizzle", desc: "shower rain and drizzle", icon: "09d" },
  {
    id: "312",
    main: "Drizzle",
    desc: "heavy intensity drizzle rain",
    icon: "09d",
  },
  { id: "311", main: "Drizzle", desc: "drizzle rain", icon: "09d" },
  {
    id: "310",
    main: "Drizzle",
    desc: "light intensity drizzle rain",
    icon: "09d",
  },
  { id: "302", main: "Drizzle", desc: "heavy intensity drizzle", icon: "09d" },
  { id: "301", main: "Drizzle", desc: "drizzle", icon: "09d" },
  { id: "300", main: "Drizzle", desc: "light intensity drizzle", icon: "09d" },
  {
    id: "232",
    main: "Thunderstorm",
    desc: "thunderstorm with heavy drizzle",
    icon: "11d",
  },
  {
    id: "231",
    main: "Thunderstorm",
    desc: "thunderstorm with drizzle",
    icon: "11d",
  },
  {
    id: "230",
    main: "Thunderstorm",
    desc: "thunderstorm with light drizzle",
    icon: "11d",
  },
  { id: "221", main: "Thunderstorm", desc: "ragged thunderstorm", icon: "11d" },
  { id: "212", main: "Thunderstorm", desc: "heavy thunderstorm", icon: "11d" },
  { id: "211", main: "Thunderstorm", desc: "thunderstorm", icon: "11d" },
  { id: "210", main: "Thunderstorm", desc: "light thunderstorm", icon: "11d" },
  {
    id: "202",
    main: "Thunderstorm",
    desc: "thunderstorm with heavy rain",
    icon: "11d",
  },
  {
    id: "201",
    main: "Thunderstorm",
    desc: "thunderstorm with rain",
    icon: "11d",
  },
  {
    id: "200",
    main: "Thunderstorm",
    desc: "thunderstorm with light rain",
    icon: "11d",
  },
];
