const arr = [
  { id: "311", main: "Drizzle", desc: "drizzle rain" },
  { id: "310", main: "Drizzle", desc: "light intensity drizzle rain" },
  { id: "302", main: "Drizzle", desc: "heavy intensity drizzle" },
  { id: "301", main: "Drizzle", desc: "drizzle" },
  { id: "300", main: "Drizzle", desc: "light intensity drizzle" },
  { id: "232", main: "Thunderstorm", desc: "thunderstorm with heavy drizzle" },
  { id: "231", main: "Thunderstorm", desc: "thunderstorm with drizzle" },
  { id: "230", main: "Thunderstorm", desc: "thunderstorm with light drizzle" },
  { id: "221", main: "Thunderstorm", desc: "ragged thunderstorm" },
  { id: "212", main: "Thunderstorm", desc: "heavy thunderstorm" },
  { id: "211", main: "Thunderstorm", desc: "thunderstorm" },
  { id: "210", main: "Thunderstorm", desc: "light thunderstorm" },
  { id: "202", main: "Thunderstorm", desc: "thunderstorm with heavy rain" },
  { id: "201", main: "Thunderstorm", desc: "thunderstorm with rain" },
  { id: "804", main: "Clouds", desc: "overcast clouds: 85-100%" },
  { id: "803", main: "Clouds", desc: "broken clouds: 51-84%" },
  { id: "802", main: "Clouds", desc: "scattered clouds: 25-50%" },
  { id: "801", main: "Clouds", desc: "few clouds: 11-25%" },
  { id: "800", main: "Clear", desc: "clear sky" },
  { id: "781", main: "Tornado", desc: "tornado" },
  { id: "771", main: "Squall", desc: "squalls" },
  { id: "762", main: "Ash", desc: "volcanic ash" },
  { id: "761", main: "Dust", desc: "dust" },
  { id: "751", main: "Sand", desc: "sand" },
  { id: "741", main: "Fog", desc: "fog" },
  { id: "731", main: "Dust", desc: "sand/ dust whirls" },
  { id: "721", main: "Haze", desc: "Haze" },
  { id: "711", main: "Smoke", desc: "Smoke" },
  { id: "701", main: "Mist", desc: "mist" },
  { id: "622", main: "Snow", desc: "Heavy shower snow" },
  { id: "621", main: "Snow", desc: "Shower snow" },
  { id: "620", main: "Snow", desc: "Light shower snow" },
  { id: "616", main: "Snow", desc: "Rain and snow" },
  { id: "615", main: "Snow", desc: "Light rain and snow" },
  { id: "613", main: "Snow", desc: "Shower sleet" },
  { id: "612", main: "Snow", desc: "Light shower sleet" },
  { id: "611", main: "Snow", desc: "Sleet" },
  { id: "602", main: "Snow", desc: "Heavy snow" },
  { id: "601", main: "Snow", desc: "Snow" },
  { id: "600", main: "Snow", desc: "light snow" },
  { id: "531", main: "Rain", desc: "ragged shower rain" },
  { id: "522", main: "Rain", desc: "heavy intensity shower rain" },
  { id: "521", main: "Rain", desc: "shower rain" },
  { id: "520", main: "Rain", desc: "light intensity shower rain" },
  { id: "511", main: "Rain", desc: "freezing rain" },
  { id: "504", main: "Rain", desc: "extreme rain" },
  { id: "503", main: "Rain", desc: "very heavy rain" },
  { id: "502", main: "Rain", desc: "heavy intensity rain" },
  { id: "501", main: "Rain", desc: "moderate rain" },
  { id: "500", main: "Rain", desc: "light rain" },
  { id: "321", main: "Drizzle", desc: "shower drizzle" },
  { id: "314", main: "Drizzle", desc: "heavy shower rain and drizzle" },
  { id: "313", main: "Drizzle", desc: "shower rain and drizzle" },
  { id: "312", main: "Drizzle", desc: "heavy intensity drizzle rain" },
  { id: "311", main: "Drizzle", desc: "drizzle rain" },
  { id: "310", main: "Drizzle", desc: "light intensity drizzle rain" },
  { id: "302", main: "Drizzle", desc: "heavy intensity drizzle" },
  { id: "301", main: "Drizzle", desc: "drizzle" },
  { id: "300", main: "Drizzle", desc: "light intensity drizzle" },
  { id: "232", main: "Thunderstorm", desc: "thunderstorm with heavy drizzle" },
  { id: "231", main: "Thunderstorm", desc: "thunderstorm with drizzle" },
  { id: "230", main: "Thunderstorm", desc: "thunderstorm with light drizzle" },
  { id: "221", main: "Thunderstorm", desc: "ragged thunderstorm" },
  { id: "212", main: "Thunderstorm", desc: "heavy thunderstorm" },
  { id: "211", main: "Thunderstorm", desc: "thunderstorm" },
  { id: "210", main: "Thunderstorm", desc: "light thunderstorm" },
  { id: "202", main: "Thunderstorm", desc: "thunderstorm with heavy rain" },
  { id: "201", main: "Thunderstorm", desc: "thunderstorm with rain" },
  { id: "200", main: "Thunderstorm", desc: "thunderstorm with light rain" },
];
